services:
  - type: web
    name: ocularai-backend
    env: python
    region: singapore   # Bangladesh এর কাছের region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
